// export const FETCH_USERS_PENDING = 'FETCH_USERS_PENDING';
// export const FETCH_USERS_SUCCESS = 'FETCH_USERS_SUCCESS';
// export const FETCH_USERS_ERROR = 'FETCH_USERS_ERROR';
//
// export const POST_LOCATION_PENDING = 'POST_LOCATION_PENDING';
// export const POST_LOCATION_ERROR = 'POST_LOCATION_ERROR';
// export const POST_LOCATION_SUCCESS = 'POST_LOCATION_SUCCESS';

export const SET_USER_CHECKED = "SET_USER_CHECKED";
export const SET_USERNAME = "SET_USERNAME";
export const SET_LOCATION = "SET_LOCATION"

export const UPDATE_USERS = "UPDATE_USERS";
export const SET_USER_ID = "SET_USER_ID";